In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
input_size = 3
hidden_size = 3
lstm = nn.LSTM(input_size,hidden_size)
inputs = [torch.randn(1,3) for _ in range(5)]
inputs
hidden = (torch.randn(1,1,3), torch.randn(1,1,3))
hidden
# inputs[1].view(1,1,-1)
# print(inputs[1])
# inputs[1].shape
for i in inputs:
    out, hidden = lstm(i.view(1,1,-1),hidden)

print(out)
print(hidden)




tensor([[[ 0.2626, -0.0716, -0.2325]]], grad_fn=<StackBackward0>)
(tensor([[[ 0.2626, -0.0716, -0.2325]]], grad_fn=<StackBackward0>), tensor([[[ 0.5211, -0.5011, -0.4972]]], grad_fn=<StackBackward0>))


In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#for reading stock market data
from pandas_datareader.data import DataReader
import yfinance as yf
from pandas_datareader import data as pdr

yf.pdr_override()

# for time stamps 
from datetime import datetime

In [7]:
# stock for analysis Apple, Google, Microsoft, Amazon
stock_list = ["AAPL", "GOOG", "MSFT", "AMZN"]
#end and start time for the data download data for one year 
end = datetime.now()
start = datetime(end.year - 1, end.month, end.day)

In [8]:
#download stock using yahoo finance
for stock in stock_list:
    globals() [stock] = yf.download(stock,start,end)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed


: 

In [4]:

#example of inputs and output from a single LSTM layer
batch_size = 32
timesteps = 10
input_features = 8
output_features = 4

inputs = torch.randn(timesteps, batch_size,input_features)
lstm = nn.LSTM(input_size=input_features, hidden_size=output_features)
h_seq_out, (h_t,c_t) = lstm(inputs)
# h_seq_out is of shape (time_steps, batch_size, out_features)
t,b,out = h_seq_out.shape
# h_seq_out[-1,:,:] means last time step for all batche_size and output_features = h_t (latst_time step)
print(h_seq_out[-1,:,:])
# print(h_t)



tensor([[-0.1280, -0.0758, -0.0529,  0.0203],
        [ 0.1132,  0.1301, -0.0903,  0.1292],
        [ 0.0151,  0.0834, -0.0718,  0.1342],
        [ 0.0670, -0.0180,  0.0679,  0.0024],
        [-0.2142,  0.0460, -0.1391,  0.0793],
        [ 0.3706,  0.1538, -0.3376, -0.0055],
        [ 0.0178,  0.3618, -0.1004,  0.1433],
        [-0.0886, -0.1460, -0.1288, -0.1311],
        [ 0.2816,  0.4119, -0.0779,  0.0524],
        [ 0.1883,  0.0462, -0.1657, -0.0946],
        [-0.0668,  0.1008, -0.1255, -0.1215],
        [ 0.2302,  0.0952,  0.0561,  0.0359],
        [ 0.1452, -0.0568, -0.1574, -0.1216],
        [ 0.3424,  0.2008, -0.1330,  0.1223],
        [ 0.2129, -0.0970, -0.0975,  0.0157],
        [ 0.2335, -0.4328, -0.0991, -0.0066],
        [-0.0185,  0.0016,  0.0893,  0.1061],
        [ 0.2041, -0.0947, -0.2690, -0.0317],
        [ 0.3411, -0.2089, -0.3320,  0.0053],
        [ 0.1345, -0.1736, -0.1279, -0.2453],
        [-0.0093,  0.0112, -0.1940, -0.0778],
        [ 0.1126, -0.0942, -0.0732

In [5]:
import torchinfo

#example for 2 LSTMs layers and 2 fully connected layers
batch_size = 32
timesteps = 12
input_features = 16
h1_features = 8
h2_features = 4
h3_features = 2
output_features = 1

class Model(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.lstm1 = LSTM(input_size=input_features, hidden_size=h1_features)
        self.lstm2 = LSTM(input_size=h1_features,hidden_size=h2_features)
        self.fc1 = nn.Linear(in_features=h2_features,out_features=h3_features)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(in_features=h3_features,out_features=output_features)
        self.sigmoid = nn.Sigmoid()

    def forward(x):
        h1, (h1_t,c1_t) = self.lstm1(x)
        h2, (h2_t,c2_t) = self.lstm2(h1)
        out = self.fc1(h2[-1::,:]) # or out = self.fc1(h2_t)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.sigmoid(out)

        return out

model = Model()

torchinfo.summary(model)

NameError: name 'LSTM' is not defined